name: WhoSudod

options:
  bundleIdPrefix: com.zats
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "27.0"

packages:
  Permiso:
    path: ../Libraries/permiso

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: 5KE88HWMKJ
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_APP_SANDBOX: NO

targets:
  WhoSudod:
    type: application
    platform: macOS
    productName: "Who Sudo'd"
    sources:
      - path: WhoSudod
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zats.WhoSudo
        PRODUCT_MODULE_NAME: WhoSudod
        PRODUCT_NAME: "Who Sudo'd"
        INFOPLIST_KEY_CFBundleDisplayName: "Who Sudo'd"
        INFOPLIST_KEY_LSUIElement: YES
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - package: Permiso
    scheme:
      testTargets:
        - WhoSudodTests

  WhoSudodTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: WhoSudodTests
    dependencies:
      - target: WhoSudod
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zats.WhoSudodTests
        GENERATE_INFOPLIST_FILE: YES

  WhoSudodLiveRequester:
    type: application
    platform: macOS
    productName: WhoSudodLiveRequester
    sources:
      - path: WhoSudodLiveRequester
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zats.WhoSudodLiveRequester
        PRODUCT_NAME: WhoSudodLiveRequester
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: WhoSudodLiveRequester
        INFOPLIST_KEY_LSUIElement: YES
